export const tabbar = [
	{
		iconPath:"/static/icon/layout_tabbar_home.png",
		selectedIconPath:"/static/icon/layout_tabbar_home_active.png",
		text:"首页",
		index:"0",
		name:"home",
		pagePath:"/pages/index/index"
	},
	{
		iconPath:"/static/icon/layout_tabbar_shop.png",
		selectedIconPath:"/static/icon/layout_tabbar_shop_active.png",
		text:"找款",
		index:"1",
		name:"search",
		pagePath:"/pages/search/index"
	},
	{
		iconPath:"/static/icon/layout_tabbar_user.png",
		selectedIconPath:"/static/icon/layout_tabbar_user_active.png",
		text:"我的",
		index:"2",
		name:"user",
		pagePath:"/pages/user/index"
	}
]